Xsl
JonathanCarona/Uebungsaufgaben pull request #7
Opened 2018-12-19 12:56 UTC by JonathanCarona

2018-12-19 13:40 UTC, JonathanCarona commented on Uebungsaufgaben/bibliothek2/src/Request.php
> +        if (isset($this->request[$key]) && $this->request[$key] !== '') {
kurze schreibweise

2018-12-19 13:40 UTC, JonathanCarona commented on Uebungsaufgaben/bibliothek2/src/Request.php
> +    public function getArrayRequest(): array
prüfen ob ein POST Request abgeschickt wurde.

2018-12-19 13:40 UTC, JonathanCarona commented on Uebungsaufgaben/bibliothek2/src/Request.php
> +    public function hasRequest(string $key): bool
Request = Parameter

2018-12-19 13:40 UTC, JonathanCarona commented on Uebungsaufgaben/bibliothek2/src/Searchresult.php
> +        if ($request->hasRequest('searchAuthor')) {
keine arbeit im konstruktor

2018-12-19 13:40 UTC, JonathanCarona commented on Uebungsaufgaben/bibliothek2/src/Searchresult.php
> +        if ($request->hasRequest('searchAuthor')) {
=> 

$this->request = $request;
$this->tool = $tool;

2018-12-19 13:40 UTC, JonathanCarona commented on Uebungsaufgaben/bibliothek2/src/Renderer.php
> +    public function getProc(): XSLTProcessor
sprechende Methoden

2018-12-19 13:40 UTC, JonathanCarona commented on Uebungsaufgaben/bibliothek2/src/index.php
> +$renderer->render($newSearch->findResult($renderer->getProc()));
parameter xslprocessor unnötig?

2018-12-19 13:40 UTC, JonathanCarona commented on Uebungsaufgaben/bibliothek2/src/Renderer.php
> +        echo $this->proc->transformToXml($dom);
return statt echo. der aufrufer kann enscheiden ob er es ausgeben will oder in eine datei speichern oder was auch immer

2018-12-19 13:40 UTC, JonathanCarona commented on Uebungsaufgaben/bibliothek2/src/RecordCreator.php
> +        $this->author = $request->getRequest('createAuthor');
keine arbeit im konstruktor

2018-12-19 13:40 UTC, JonathanCarona commented on Uebungsaufgaben/bibliothek2/src/RecordCreator.php
> +        $lastItem = $xpath->query('//book[last()]');
//Refactor => getNextId()

2018-12-19 13:40 UTC, JonathanCarona commented on Uebungsaufgaben/bibliothek2/src/RecordCreator.php
> +        $author = $dom->createElement('author', $this->author);
validierung der werte

2018-12-19 13:40 UTC, JonathanCarona commented on Uebungsaufgaben/bibliothek2/src/RecordCreator.php
> +        $author = $dom->createElement('author', $this->author);
escapen der werte?

2019-01-07 07:05 UTC, FloEberle requested changes
ich glaube du hast nicht alles commitet oder gepusht.. hast du das neue routing implementiert?

2019-01-07 07:05 UTC, FloEberle commented on Uebungsaufgaben/bibliothek2/src/Request.php
> +        if (!empty($errors)) {
return !empty($errors);

2019-01-07 07:05 UTC, FloEberle commented on Uebungsaufgaben/bibliothek2/src/Request.php
> +        return (isset($this->request[$key]) && $this->request[$key] !== '') ? true : false;
return () ...

2019-01-07 07:05 UTC, FloEberle commented on Uebungsaufgaben/bibliothek2/src/Router.php
> +class Router
fertig implementieren?

2019-01-14 16:49 UTC, merged